/*
-- Query: select * from books
LIMIT 0, 1000

-- Date: 2023-07-14 01:22
*/
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (1,'9788173711466','Wings of fire: An autobiography','A. P. J. Abdul Kalam','Motivation','Sangam Books Ltd','1969-12-31','1st',12,15,10,'Reading books is a kind of enjoyment. Reading books is a good habit. We bring you a different kinds of books. You can carry this book where ever you want. It is easy to carry. It can be an ideal gift to yourself and to your loved ones. Care instruction keep away from fire.',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (2,'0143130722','Ikigai: The Japanese Secret to a Long and Happy Life','Héctor García,Francesc Miralles','Motivation','Penguin Life','1969-12-31','Illustrated',15.5,18.45,8,'Discover your ikigai, pronounced ee-key-guy, and unlock a longer, more fulfilling life filled with purpose and joy. With over 1.5 million copies sold worldwide, this international bestseller has captivated readers seeking a more meaningful existence. Business Insider states that identifying your ikigai is key for individuals yearning for more satisfying careers, while Forbes highlights the pandemic\'s unintended yet positive impact in prompting people to reassess their lives and find their personal ikigai. Embrace this opportune time, live your best life, and cultivate the active mindset that will inspire you to thrive for a hundred years, as emphasized by a Japanese proverb.',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (3,'1590035003','The Book of Awakening: Having the Life You Want by Being Present to the Life You Have','Mark Nepo','Motivation','Red Wheel','1969-12-31','20th',11.8,13.99,7,'A new edition of the #1 NYT’s bestseller by Mark Nepo, who has been called “one of the finest spiritual guides of our time” and “a consummate storyteller.” Philosopher-poet and cancer survivor Mark Nepo opens a new season of freedom and joy―an escape from deadening, asleep-at-the wheel sameness―that is both profound and clarifying.',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (4,'1544534078','Never Finished: Unshackle Your Mind and Win the War Within','David Goggins','Motivation','Lioncrest Publishing','1969-12-31','1st',11.8,13.99,7,'In Never Finished David Goggins eye-opening memoir, he goes beyond his bestselling book, Can\'t Hurt Me, to awaken readers to the untapped potential within themselves. Goggins invites you into his Mental Lab, unveiling the philosophy, psychology, and strategies that shattered his perceived limits and revealed that greatness knows no bounds. ',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (5,'0757316425','The Undefeated Mind: On the Science of Constructing an Indestructible Self','Dr. Alex Lickerman MDs','Motivation','Audible Studios','1969-12-31','1st',15.8,17.89,50,'While many self-help authors emphasize personal development for happiness, they often overlook the crucial aspect of cultivating hardiness. However, new scientific research reveals that resilience can be developed through intentional actions. Dr. Alex Lickerman highlights the transformative power of adversity, asserting that wisdom gained from challenges can serve as the catalyst for personal growth and strength.',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (6,'125030170X','The Silent Patient','Alex Michaelides','Suspense','Macmillan Audio','1969-12-31','2nd',10.8,13,20,' Immerse yourself in the gripping psychological thriller, The Housemaid\'s Secret by Freida McFadden, where secrets and suspense lurk within the luxurious penthouse of the enigmatic Garrick family. As the new housemaid, the protagonist uncovers unsettling clues and a mysterious illness, leading her to make a fateful promise that sets off a chain of events with unforeseen consequences. Prepare for a shocking twist that will keep you on the edge of your seat until the very end',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (7,'1538742578','The Housemaid','Freida McFadden','Suspense','Hachette UK - Bookouture','1969-12-31','2nd',15.3,20,45,' Get ready for the addictive and bestselling psychological thriller, The Housemaid by Freida McFadden, as it takes the literary world by storm. Immerse yourself in the gripping story of a housemaid entangled in a web of secrets, manipulation, and a twisted obsession that unfolds within the Winchesters\' luxurious home. With a shocking twist that has captivated readers and social media users alike, this chilling tale is a must-read for fans of Ruth Ware, Lisa Jewell, and Verity.',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (8,'1957635010','Hunting Adeline (Cat and Mouse Duet)','H. D. Carlton','Suspense','H. D. Carlton','1969-12-31','2nd',9.3,15.97,0,' Experience the thrilling conclusion to the Cat and Mouse Duet with The Diamond and The Hunter. As the characters navigate a treacherous world of deception and betrayal, they fight to reclaim their identities and seek justice. Prepare for intense action, relentless pursuit, and the unyielding wrath of those seeking revenge. Make sure to read Haunting Adeline first to fully immerse yourself in this gripping duet.',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (9,'1957635010','Hunting Adeline (Cat and Mouse Duet)','H. D. Carlton','Suspense','H. D.Jack','1969-12-31','2nd',9.3,15.97,12,' Experience the thrilling conclusion to the Cat and Mouse Duet with The Diamond and The Hunter. As the characters navigate a treacherous world of deception and betrayal, they fight to reclaim their identities and seek justice. Prepare for intense action, relentless pursuit, and the unyielding wrath of those seeking revenge. Make sure to read Haunting Adeline first to fully immerse yourself in this gripping duet.',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (10,'1501154656','Then She Was Gone: A Novel','Lisa Jewell','Suspense','H. D.Jack','1969-12-31','Reprint',9.3,11.34,12,' #1 NEW YORK TIMES BESTSELLER From the New York Times bestselling author of Invisible Girl and The Truth About Melody Browne comes a “riveting” (PopSugar) and “acutely observed family drama” (People) that delves into the lingering aftermath of a young girl’s disappearance.',?);
INSERT INTO `` (`BookID`,`isbn`,`title`,`author`,`category`,`publisher`,`Publication_Year`,`edition`,`buying_price`,`selling_price`,`Quantity`,`description`,`image_data`) VALUES (11,'1503905128','The Perfect Child','Lucinda Berry','Suspense','H. D.J','1969-12-31','Reprint',7.3,10.99,12,' #1 NEW YORK TIMES BESTSELLER From the New York Times bestselling author of Invisible Girl and The Truth About Melody Browne comes a “riveting” (PopSugar) and “acutely observed family drama” (People) that delves into the lingering aftermath of a young girl’s disappearance.',?);
